language: python
install:
  - python -mpip install pytest pytest-cov
  - python -mpip install scipy matplotlib
  - python -mpip install codecov coverage
script: python -mpytest --cov=./
after_success:
  - codecov
