language: python

env:
  # - MATPLOTLIB_VERSION=3.0.3  # This version has a bug for text rotations.
  - MATPLOTLIB_VERSION=3.1.1

before_install:
  - sudo apt-get -y install ghostscript inkscape

install:
  - python -mpip install matplotlib==$MATPLOTLIB_VERSION
  - python -mpip install pytest pytest-cov
  - python -mpip install codecov coverage
script: python -mpytest -ra --cov=./ --log-level=DEBUG
after_success:
  - codecov
